-- MySQL Script generated by MySQL Workbench
-- mar 15 oct 2019 15:40:10 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Langues`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Langues` (
  `upsid` INT NOT NULL,
  `nom` VARCHAR(100) NULL,
  `biblio` TEXT NULL,
  PRIMARY KEY (`upsid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Phonemes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Phonemes` (`IPA` VARCHAR(10) NOT NULL,`description` TEXT NULL,PRIMARY KEY (`IPA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Phonemes_Langues`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Phonemes_Langues` (`upsid` INT NOT NULL,`IPA` VARCHAR(10) NOT NULL,INDEX `upsid_idx` (`upsid` ASC),INDEX `IPA_idx` (`IPA` ASC),PRIMARY KEY (`upsid`, `IPA`),CONSTRAINT `upsid` FOREIGN KEY (`upsid`) REFERENCES `mydb`.`Langues` (`upsid`) ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT `IPA` FOREIGN KEY (`IPA`) REFERENCES `mydb`.`Phonemes` (`IPA`) ON DELETE NO ACTION ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Branches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Branches` (`superfamille` VARCHAR(100) NOT NULL,`famille` VARCHAR(100) NOT NULL,PRIMARY KEY (`superfamille`, `famille`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Langues_Branches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Langues_Branches` (`famille` VARCHAR(100) NOT NULL,`upsid` INT NOT NULL,PRIMARY KEY (`famille`, `upsid`), INDEX `upsid_idx` (`upsid` ASC), CONSTRAINT `upsid` FOREIGN KEY (`upsid`) REFERENCES `mydb`.`Langues` (`upsid`) ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT `famille` FOREIGN KEY (`famille`) REFERENCES `mydb`.`Branches` (`famille`) ON DELETE NO ACTION ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
